/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crudgestoralumnos;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.io.FileWriter;

import java.io.FileOutputStream;
import javax.swing.ListModel;

import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dimension;

import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;

import javax.swing.ListModel;

/**
 *
 * @author dogza
 */
public class frmAlumno extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(frmAlumno.class.getName());

    /**
     * Creates new form frmAlumno
     */
    public frmAlumno() {
        initComponents();
    // 1. Quitamos los tamaños fijos de la lista (para que no corte el texto largo)
    this.lstAlumnos.setPreferredSize(null);
    this.lstAlumnos.setMinimumSize(null);
    this.lstAlumnos.setMaximumSize(null);
    
    // 2. CONGELAMOS EL CONTENEDOR (jScrollPane2) al tamaño que tú querías (ej. 150x120 o el que te guste)
    Dimension tamanoFijoScroll = new Dimension(250, 120); // Le di un poco más de ancho (250) para que sea cómodo
    this.jScrollPane2.setPreferredSize(tamanoFijoScroll);
    this.jScrollPane2.setMinimumSize(tamanoFijoScroll);
    this.jScrollPane2.setMaximumSize(tamanoFijoScroll);
    
    // 3. Forzamos a que aparezca la barra horizontal cuando el texto se salga del JScrollPane
    this.jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
    this.lstAlumnos.setLayoutOrientation(javax.swing.JList.VERTICAL);
    }

    clsAlumno updateAlumno;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnEliminar = new java.awt.Button();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        lblCurp = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        chkEstatus2 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        txtNombre1 = new javax.swing.JTextField();
        txtMatricula1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtCurp1 = new javax.swing.JTextField();
        txtTelefono1 = new javax.swing.JTextField();
        btnActualizar = new java.awt.Button();
        chkEstatus1 = new javax.swing.JCheckBox();
        txtFecha1 = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtBuscarMatricula = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAlumnos = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        txtCurp = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnGuardar = new java.awt.Button();
        chkEstatus = new javax.swing.JCheckBox();
        txtFecha = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiImportar = new javax.swing.JMenuItem();
        jmiJson = new javax.swing.JMenuItem();
        jmiReporte = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Eliminacion de Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel10.setText("Nombre");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel11.setText("Matricula");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel12.setText("Estatus");

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel13.setText("CURP");

        btnEliminar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnEliminar.setLabel("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel6.setText("Fecha de Nacimiento");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel7.setText("Telefono");

        lblNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblNombre.setText("Nombre...");

        lblMatricula.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblMatricula.setText("Matricula...");

        lblCurp.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblCurp.setText("CURP...");

        lblFechaNacimiento.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblFechaNacimiento.setText("Fecha...");

        lblTelefono.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblTelefono.setText("Telefono...");

        chkEstatus2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        chkEstatus2.setText("Activo");
        chkEstatus2.addActionListener(this::chkEstatus2ActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(chkEstatus2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCurp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGap(18, 18, 18)
                        .addComponent(lblMatricula)
                        .addGap(16, 16, 16)
                        .addComponent(chkEstatus2)
                        .addGap(18, 18, 18)
                        .addComponent(lblCurp)
                        .addGap(18, 18, 18)
                        .addComponent(lblFechaNacimiento)
                        .addGap(18, 18, 18)
                        .addComponent(lblTelefono)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Actualizacion de Alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N

        txtNombre1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        txtMatricula1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel21.setText("CURP");

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel17.setText("Nombre");

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel20.setText("Estatus");

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel19.setText("Fecha de nacimiento");

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel16.setText("Telefono");

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel18.setText("Matricula");

        txtCurp1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        txtTelefono1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        btnActualizar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnActualizar.setLabel("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        chkEstatus1.setText("Activo");
        chkEstatus1.addActionListener(this::chkEstatus1ActionPerformed);

        txtFecha1.addActionListener(this::txtFecha1ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel16)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMatricula1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtNombre1)
                    .addComponent(txtCurp1)
                    .addComponent(txtTelefono1)
                    .addComponent(chkEstatus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFecha1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMatricula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkEstatus1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCurp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Consulta de Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel5.setText("Matricula");

        txtBuscarMatricula.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        lstAlumnos.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lstAlumnos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ulises de la Cruz...", "Ethan Alfredo... ", "Jorge Alberto...", " ", " ", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstAlumnos.addListSelectionListener(this::lstAlumno);
        jScrollPane2.setViewportView(lstAlumnos);

        jScrollPane3.setViewportView(jScrollPane2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBuscarMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Registro de Alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel2.setText("Matricula");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel3.setText("Estatus");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel4.setText("CURP");

        txtNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        txtMatricula.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        txtCurp.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel14.setText("Fecha de nacimiento");

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel15.setText("Telefono");

        txtTelefono.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtTelefono.addActionListener(this::txtTelefonoActionPerformed);

        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnGuardar.setLabel("GUARDAR");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        chkEstatus.setText("Activo");
        chkEstatus.addActionListener(this::chkEstatusActionPerformed);

        txtFecha.addActionListener(this::txtFechaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(txtNombre)
                        .addComponent(txtMatricula))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(chkEstatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCurp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(txtFecha)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkEstatus))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        jmiImportar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jmiImportar.setText("Importar CSV");
        jmiImportar.addActionListener(this::jmiImportarActionPerformed);
        jMenu1.add(jmiImportar);

        jmiJson.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jmiJson.setText("Exportar Json");
        jmiJson.addActionListener(this::jmiJsonActionPerformed);
        jMenu1.add(jmiJson);

        jmiReporte.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jmiReporte.setText("Reporte PDF");
        jmiReporte.addActionListener(this::jmiReporteActionPerformed);
        jMenu1.add(jmiReporte);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Informacion");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFecha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFecha1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (updateAlumno == null) {
            JOptionPane.showMessageDialog(this, "Selecciona un cliente de la lista antes de eliminar.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Estas seguro que deseas eliminar el registro " +
                        updateAlumno.getNombre()+"?",
                "Eliminacion de clientes",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(respuesta == JOptionPane.YES_OPTION){
            updateAlumno.eliminar();
            btnBuscarActionPerformed(null);
            updateAlumno = null;
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jmiJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiJsonActionPerformed
 try {
        // Obtener lista de alumnos
        clsAlumno alumno = new clsAlumno();
        javax.swing.ListModel<String> lista = alumno.LlenarLista();

        List<clsAlumno> alumnos = new ArrayList<>();

        for (int i = 0; i < lista.getSize(); i++) {

            String registro = lista.getElementAt(i);
            String[] datos = registro.split("\\|");

            String nombre = datos[0].replace("Nombre: ", "").trim();
            String matricula = datos[1].replace("Matricula: ", "").trim();
            boolean estatus = Boolean.parseBoolean(
                    datos[2].replace("Estatus: ", "").trim()
            );
            String curp = datos[3].replace("Curp: ", "").trim();

            String fechaTexto =
                    datos[4].replace("Fecha de Nacimiento: ", "").trim();

            DateTimeFormatter formato =
                    DateTimeFormatter.ofPattern("yyyy-MM-dd");

            LocalDate fecha =
                    LocalDate.parse(fechaTexto, formato);

            String telefono =
                    datos[5].replace("Telefono: ", "").trim();

            clsAlumno nuevo =
                    new clsAlumno(nombre,
                                  matricula,
                                  estatus,
                                  curp,
                                  fecha,
                                  telefono);

            alumnos.add(nuevo);
        }

        // Convertir lista completa a JSON bonito
        Gson gson =
                new GsonBuilder()
                .setPrettyPrinting()
                .create();

        String json =
                gson.toJson(alumnos);

        // Guardar archivo JSON
        FileWriter writer =
                new FileWriter("alumnos.json");

        writer.write(json);
        writer.close();

        JOptionPane.showMessageDialog(
                this,
                "Exportación JSON realizada correctamente"
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

        System.out.println(e);
        }      
    }//GEN-LAST:event_jmiJsonActionPerformed

    private void jmiReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiReporteActionPerformed
     Font fuenteTitulo =
            FontFactory.getFont(
                    FontFactory.HELVETICA_BOLD,
                    18,
                    BaseColor.BLACK
            );

    Font fuenteSubtitulo =
            FontFactory.getFont(
                    FontFactory.HELVETICA,
                    12,
                    BaseColor.DARK_GRAY
            );

    Font fuenteCabecera =
            FontFactory.getFont(
                    FontFactory.HELVETICA_BOLD,
                    12,
                    BaseColor.WHITE
            );

    Font fuenteTotal =
            FontFactory.getFont(
                    FontFactory.HELVETICA_BOLD,
                    13,
                    BaseColor.BLUE
            );


    Document documento =
            new Document();

    try{

        PdfWriter.getInstance(
                documento,
                new FileOutputStream("Reporte_Alumnos.pdf")
        );

        documento.open();


        // LOGO
        try{

            Image logo =
                    Image.getInstance("logo.jpg");

            logo.scaleToFit(120,80);

            logo.setAlignment(
                    Element.ALIGN_RIGHT
            );

            documento.add(logo);

        }
        catch(Exception e){

            System.out.println(
             "No se encontró logo.jpg"
            );

        }


        // ENCABEZADO
        Paragraph escuela =
                new Paragraph(
                 "SISTEMA DE GESTION DE ALUMNOS",
                 fuenteTitulo
                );

        documento.add(escuela);


        Paragraph subtitulo =
                new Paragraph(
                 "Reporte General de Alumnos",
                 fuenteSubtitulo
                );

        documento.add(subtitulo);


        String fechaActual =
                new SimpleDateFormat(
                        "dd/MM/yyyy HH:mm"
                ).format(new Date());


        Paragraph fecha =
                new Paragraph(
                 "Fecha: "
                 + fechaActual,
                 fuenteSubtitulo
                );

        fecha.setSpacingAfter(20f);

        documento.add(fecha);



        // TABLA
        PdfPTable tabla =
                new PdfPTable(6);

        tabla.setWidthPercentage(100);

        tabla.setWidths(
                new float[]{
                        4f,
                        2f,
                        2f,
                        3f,
                        3f,
                        3f
                }
        );


        String[] cabeceras = {

                "NOMBRE",
                "MATRICULA",
                "ESTATUS",
                "CURP",
                "FECHA",
                "TELEFONO"

        };


        for(String texto:cabeceras){

            PdfPCell celda =
                    new PdfPCell(
                      new Phrase(
                              texto,
                              fuenteCabecera
                      )
                    );

            celda.setBackgroundColor(
             new BaseColor(41,128,185)
            );

            celda.setHorizontalAlignment(
                    Element.ALIGN_CENTER
            );

            celda.setPadding(8f);

            tabla.addCell(celda);
        }



        clsAlumno alumno =
                new clsAlumno();

        ListModel<String> lista =
                alumno.LlenarLista();

        int activos = 0;



        for(int i=0;i<lista.getSize();i++){

            String registro =
                    lista.getElementAt(i);

            String datos[] =
                    registro.split("\\|");


            tabla.addCell(
             datos[0]
             .replace("Nombre: ","")
             .trim()
            );


            tabla.addCell(
             datos[1]
             .replace("Matricula: ","")
             .trim()
            );


            String estatus =
             datos[2]
             .replace("Estatus: ","")
             .trim();


            PdfPCell celdaStatus;

            if(estatus.equalsIgnoreCase("true")){

                celdaStatus =
                 new PdfPCell(
                  new Phrase("Activo")
                 );

                activos++;

            }
            else{

                celdaStatus =
                 new PdfPCell(
                  new Phrase("Inactivo")
                 );

            }

            celdaStatus.setHorizontalAlignment(
                    Element.ALIGN_CENTER
            );

            tabla.addCell(celdaStatus);



            tabla.addCell(
             datos[3]
             .replace("Curp: ","")
             .trim()
            );


            tabla.addCell(
             datos[4]
             .replace(
               "Fecha de Nacimiento: ",
               ""
             )
             .trim()
            );


            tabla.addCell(
             datos[5]
             .replace(
               "Telefono: ",
               ""
             )
             .trim()
            );

        }


        documento.add(tabla);



        int total =
                lista.getSize();

        Paragraph resumen =
                new Paragraph(

                 "\nTotal alumnos: "
                 + total +

                 "\nAlumnos activos: "
                 + activos +

                 "\nAlumnos inactivos: "
                 + (total-activos),

                 fuenteTotal
                );


        resumen.setAlignment(
                Element.ALIGN_RIGHT
        );


        documento.add(resumen);


        documento.close();


        JOptionPane.showMessageDialog(
                this,
                "PDF generado correctamente"
        );


    }
    catch(Exception e){

        JOptionPane.showMessageDialog(
                this,
                "Error: "
                + e.getMessage()
        );

    }

    }//GEN-LAST:event_jmiReporteActionPerformed

    private void jmiImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiImportarActionPerformed
        // TODO add your handling code here:
                int respuesta = JOptionPane.showConfirmDialog(this,
                "Es importante que el archivo a importar tenga el nombre " + 
                    "alumnos.csv y se encuentra en la raiz del proyecto",
                "Importanción de Datos desde el archivo CSV",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(respuesta == JOptionPane.YES_OPTION){
            clsCSV cCsv = new clsCSV();
            cCsv.importarClientes();
        }
    }//GEN-LAST:event_jmiImportarActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtTelefonoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String strNombre = txtNombre.getText().trim();
        String strMatricula = txtMatricula.getText().trim();
        boolean strEstatus = chkEstatus.isSelected();
        String strCurp = txtCurp.getText().trim();
        String strFecha = txtFecha.getText().trim();
        String strTelefono = txtTelefono.getText().trim();
        
        String fechaLimpia = strFecha.replace("/", "").replace("_", "").trim();
        
        // 2. Validación de longitud exacta (10 caracteres)
        if (strTelefono.length() != 10) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "El número de teléfono debe tener exactamente 10 dígitos.", 
                "Error de validación", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Detiene la ejecución si no cumple
        }

        // 3. Validación opcional pero recomendada: que sean solo dígitos
        if (!strTelefono.matches("\\d+")) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "El teléfono solo debe contener números.", 
                "Error de validación", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Detiene la ejecución si contiene letras o símbolos
        }
        
        // Validacion para campos sin llenar al guardar
        if (strNombre.isEmpty() || strMatricula.isEmpty() ||
                strCurp.isEmpty() || fechaLimpia.isEmpty() || strTelefono.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
            return; // Detenemos la ejecución aquí
        }

        LocalDate fechaNac = null;
        try {
            DateTimeFormatter formato = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
            fechaNac = LocalDate.parse(strFecha, formato);
        } catch (java.time.format.DateTimeParseException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "La fecha ingresada no es válida. Use el formato Día/Mes/Año (ej: 18/02/2004).",
                "Error de Fecha",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return; // Detiene el guardado si la fecha está mal
    }

        clsAlumno cAlumno = new clsAlumno(strNombre, strMatricula, strEstatus, strCurp, fechaNac, strTelefono);
        cAlumno.guardar();
        javax.swing.JOptionPane.showMessageDialog(this, "Alumno guardado con éxito.");
    }// GEN-LAST:event_btnGuardarActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtFechaActionPerformed

    private void chkEstatusActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void chkEstatus1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void chkEstatus2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        clsAlumno cAlumno = new clsAlumno();
    
        // 1. Obtener la matrícula y quitar espacios en blanco
        String matriculaBusqueda = txtBuscarMatricula.getText().trim();
    
        // 2. Verificar si el campo está vacío o no
        if (matriculaBusqueda.isEmpty()) {
        // Si está vacío, busca a todos los alumnos (Búsqueda General)
        lstAlumnos.setModel(cAlumno.LlenarLista());
        } else {
        // Si tiene texto, busca solo esa matrícula (Búsqueda Específica)
        // Nota: Asegúrate de crear este método en tu clase clsAlumno
        lstAlumnos.setModel(cAlumno.LlenarListaPorMatricula(matriculaBusqueda));
        }
        
    }// GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        String fechaVisual = txtFecha1.getText().trim();
    
        // 2. Reemplazar guiones por barras automáticamente
        String fechaCorregida = fechaVisual.replace('-', '/');
        
        DateTimeFormatter formato = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate fechaNac = java.time.LocalDate.parse(fechaCorregida, formato);
        
        if (updateAlumno != null) {
            updateAlumno.actualizar(txtNombre1.getText(), txtMatricula1.getText(), chkEstatus1.isSelected(),
                    txtCurp1.getText(), fechaNac, txtTelefono1.getText());
            javax.swing.JOptionPane.showMessageDialog(this, "Alumno actualizado con exito");
            btnBuscarActionPerformed(null);
        }
    }// GEN-LAST:event_btnActualizarActionPerformed

    private void lstAlumno(javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_lstAlumno
        // TODO add your handling code here:
        if (!evt.getValueIsAdjusting()) {

            // Le asigna el valor de la lista seleccionado
            String registroSeleccionado = lstAlumnos.getSelectedValue();

            if (registroSeleccionado == null) {
                return;
            }

            // VALIDACIÓN CLAVE: Verificar si contiene "|" antes de intentar separar y mapear
            if (registroSeleccionado.contains("|")) {
            
                // Separar los datos por el caracter especial
                String[] datos = registroSeleccionado.split("\\|");

                // Nos aseguramos de que tenga las 6 partes que componen al alumno
                if (datos.length >= 6) {
                
                    String nombre = datos[0].replace("Nombre: ", "").trim();
                    String matricula = datos[1].replace("Matricula: ", "").trim();
                    String estatus = datos[2].replace("Estatus: ", "").trim();
                    String curp = datos[3].replace("Curp: ", "").trim();
                    String fecha = datos[4].replace("Fecha de Nacimiento: ", "").trim();
                    String telefono = datos[5].replace("Telefono: ", "").trim();
                
                    chkEstatus2.setEnabled(false);
                
                    // Se toma del txt como yyyy-MM-dd
                    DateTimeFormatter formatoEntrada = java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd");
                    LocalDate fechaNac = java.time.LocalDate.parse(fecha, formatoEntrada);
                
                    // Se transforma en el label
                    DateTimeFormatter formatoVista = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                    String fechaFormateada = fechaNac.format(formatoVista);
                
                    // Llenamos los campos de texto
                    txtNombre1.setText(nombre);
                    txtMatricula1.setText(matricula);
                    chkEstatus1.setSelected(Boolean.parseBoolean(estatus));
                    txtCurp1.setText(curp);
                    txtFecha1.setText(fechaFormateada);
                    txtTelefono1.setText(telefono);

                    // Llenamos los lbl
                    lblNombre.setText(nombre);
                    lblMatricula.setText(matricula);
                    chkEstatus2.setSelected(Boolean.parseBoolean(estatus));
                    lblCurp.setText(curp);
                    lblFechaNacimiento.setText(fechaFormateada);
                    lblTelefono.setText(telefono);

                    // Llenamos el objeto con los valores originales
                    updateAlumno = new clsAlumno(nombre, matricula, Boolean.parseBoolean(estatus), curp, fechaNac, telefono);
                }
        } else {
            // OPCIONAL: Si haces clic en el mensaje de error o en un renglón vacío, 
            // puedes limpiar los campos para que no se queden los datos del alumno anterior.
            limpiarCamposFormulario(); 
        }
    }
    }
    private void limpiarCamposFormulario() {
        // 1. Limpiar campos de texto del panel de Actualización
        txtNombre1.setText("");
        txtMatricula1.setText("");
        chkEstatus1.setSelected(false);
        txtCurp1.setText("");
        txtFecha1.setText("");
        txtTelefono1.setText("");

        // 2. Limpiar las etiquetas (Labels) del panel de Eliminación
        lblNombre.setText("Nombre...");
        lblMatricula.setText("Matricula...");
        chkEstatus2.setSelected(false);
        lblCurp.setText("CURP...");
        lblFechaNacimiento.setText("Fecha...");
        lblTelefono.setText("Telefono...");
        
        // 3. Anular el objeto de actualización para que no guarde basura
        updateAlumno = null;
    }

    // GEN-LAST:event_lstAlumno

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmAlumno().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnActualizar;
    private javax.swing.JButton btnBuscar;
    private java.awt.Button btnEliminar;
    private java.awt.Button btnGuardar;
    private javax.swing.JCheckBox chkEstatus;
    private javax.swing.JCheckBox chkEstatus1;
    private javax.swing.JCheckBox chkEstatus2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem jmiImportar;
    private javax.swing.JMenuItem jmiJson;
    private javax.swing.JMenuItem jmiReporte;
    private javax.swing.JLabel lblCurp;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JList<String> lstAlumnos;
    private javax.swing.JTextField txtBuscarMatricula;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtCurp1;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JFormattedTextField txtFecha1;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtMatricula1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono1;
    // End of variables declaration//GEN-END:variables
}
